#!/usr/bin/env bash
# Set the Internal Field Separator (IFS) to colon to split fields in /etc/passwd
IFS=":"
# Open /etc/passwd file for reading
while IFS=":" read -r username _ _ _ gecos homedir shell _; do
  # Extract the user information from the GECOS field
  IFS="," read -ra gecos_fields <<< "$gecos"
  group_name="${gecos_fields[1]}"
  user_info="${gecos_fields[4]}"

  # Display the formatted information
  echo "The user $username is part of the $group_name gang,"
  echo "lives in $homedir and rides $shell."
  echo "More info about the user here: $user_info"
  echo
done < /etc/passwd

