#!/usr/bin/env bash
# Set the input field separator (IFS) to ":"
IFS=":"

# Open the /etc/passwd file for reading
exec 3< /etc/passwd

# Read each line from the file
while read -u 3 -r username _ uid gid _ home shell; do
    # Extract user ID info from the username
    uid_info=$(grep "^$username:" /etc/passwd | cut -d: -f5)

    # Extract the user's password (usually 'x')
    password="x"

    # Print formatted output
    echo "The user $username is part of the $gid gang, lives in $home, and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $uid_info"
done

# Close the file descriptor
exec 3<&-
