#!/usr/bin/env bash
# Use awk to group, count, and format the data
awk '{ ip_code_count[$1" "$9]++ }
     END {
         for (entry in ip_code_count) {
             split(entry, parts, " ")
             printf "%4d %s %s\n", ip_code_count[entry], parts[1], parts[2]
         }
     }' apache-access.log | sort -nr
