#!/usr/bin/env bash

# Initialize a counter
count=0

# Use a while loop to display "Best School" 10 times
while [ $count -lt 10 ]; do
  echo "Best School"
  # Increment the counter
  ((count++))
done

