#!/usr/bin/env bash
# using If and while loop
count=0
while [ $count -lt 10 ]; do
  if [ $count -eq 8 ]; then
    echo "Best School"
    echo "Hi"
  else
    echo "Best School"
  fi
  ((count++))
done

