#!/usr/bin/env bash
#recover
hour=0
minute=1
while [ "$hour" -le 12 ]; do
  echo "Hour: $hour"
  while [ "$minute" -le 59 ]; do
    echo "$minute"
    ((minute++))
  done
  ((hour++))
  minute=1
done | head -n 70
