#!/usr/bin/env bash
# file
file="school"
if [ -e "$file" ]; then
  # Check if the file exists
  echo "school file exists"

  if [ -s "$file" ]; then
    # Check if the file is not empty
    echo "school file is not empty"

    if [ -f "$file" ]; then
      # Check if the file is a regular file
      echo "school is a regular file"
    fi
  else
    echo "school file is empty"
  fi
else
  echo "school file does not exist"
fi
