#!/usr/bin/env bash
#killing some infinite loop process
pids=$(pgrep -f infinity)

if [ -n "$pids" ]; then
    # Loop through each PID and send a kill signal to terminate the processes
    for pid in $pids; do
        kill "$pid"
    done
else
    echo "No matching processes found."
fi

